const itineraryData = [
    {
      date: "Thu, July 17",
      location: "Israel → London",
      googleMapsQuery: "London Victoria Station, London, UK",
      type: "work-day",
      status: "Work Day",
      weather: "cloudy",
      weatherIcon: "☁️",
      temperature: "18°C",
      activities: "Work from home\nFlight departure at 17:00, arrive London 20:20",
      accommodation: "London Victoria Station Hotel",
      emoji: "✈️",
      quickLinks: [
        {
          type: "hotel",
          text: "🏨 London Victoria Hotel",
          file: "July17_Hotel_London_Victoria.pdf",
        },
      ],
    },
    {
      date: "Fri, July 18",
      location: "London → Wedding Venue",
      googleMapsQuery: "Royal Berkshire Hotel, Ascot, UK",
      type: "wedding-day",
      status: "Wedding",
      weather: "partly-cloudy",
      weatherIcon: "⛅",
      temperature: "22°C",
      activities: "Morning: Travel to wedding venue\nWedding ceremony & celebration",
      accommodation: "Royal Berkshire Hotel",
      emoji: "💒",
    },
    {
      date: "Sat, July 19",
      location: "Royal Berkshire",
      googleMapsQuery: "Royal Berkshire Hotel, Ascot, UK",
      type: "wedding-day",
      status: "Wedding",
      weather: "sunny",
      weatherIcon: "☀️",
      temperature: "25°C",
      activities: "Relax / post-wedding activities",
      accommodation: "Royal Berkshire Hotel",
      emoji: "🛏️",
    },
    {
      date: "Sun, July 20",
      location: "Back to London",
      googleMapsQuery: "CitizenM Tower of London, London, UK",
      type: "weekend",
      status: "Day Off",
      weather: "cloudy",
      weatherIcon: "☁️",
      temperature: "19°C",
      activities: "Check-in to London hotel",
      accommodation: "CitizenM Tower of London Hotel (3 nights)",
      emoji: "🏙️",
      quickLinks: [
        {
          type: "hotel",
          text: "🏨 CitizenM Tower of London",
          file: "July20-22_Hotel_CitizenM_London.pdf",
        },
      ],
    },
    {
      date: "Mon, July 21",
      location: "London",
      googleMapsQuery: "London, UK",
      type: "work-day",
      status: "Work Day",
      weather: "rainy",
      weatherIcon: "🌧️",
      temperature: "16°C",
      activities: "Remote work day",
      accommodation: "CitizenM Tower of London",
      emoji: "📍",
    },
    {
      date: "Tue, July 22",
      location: "London",
      googleMapsQuery: "London, UK",
      type: "work-day",
      status: "Work Day",
      weather: "partly-cloudy",
      weatherIcon: "⛅",
      temperature: "20°C",
      activities: "Remote work day",
      accommodation: "CitizenM Tower of London",
      emoji: "📍",
    },
    {
      date: "Wed, July 23",
      location: "London → Paris",
      googleMapsQuery: "CitizenM Paris Gare de Lyon, Paris, France",
      type: "work-day",
      status: "Work Day",
      weather: "sunny",
      weatherIcon: "☀️",
      temperature: "26°C",
      activities: "Train to Paris\nRemote work day",
      accommodation: "CitizenM Paris Gare de Lyon (3 nights)",
      emoji: "🚄",
      quickLinks: [
        {
          type: "train",
          text: "🚄 London → Paris Train",
          file: "July23_Train_London_Paris.pdf",
        },
        {
          type: "hotel",
          text: "🏨 CitizenM Paris",
          file: "July23-25_Hotel_CitizenM_Paris.pdf",
        },
      ],
    },
    {
      date: "Thu, July 24",
      location: "Paris",
      googleMapsQuery: "Paris, France",
      type: "work-day",
      status: "Work Day",
      weather: "sunny",
      weatherIcon: "☀️",
      temperature: "28°C",
      activities: "Remote work day",
      accommodation: "CitizenM Paris Gare de Lyon",
      emoji: "🇫🇷",
    },
    {
      date: "Fri, July 25",
      location: "Paris",
      googleMapsQuery: "Paris, France",
      type: "weekend",
      status: "Day Off",
      weather: "sunny",
      weatherIcon: "☀️",
      temperature: "30°C",
      activities: "Explore the city, museums, cafes",
      accommodation: "CitizenM Paris Gare de Lyon",
      emoji: "🇫🇷",
    },
    {
      date: "Sat, July 26",
      location: "Paris → Chabeuil",
      googleMapsQuery: "Chabeuil, France",
      type: "weekend",
      status: "Day Off",
      weather: "sunny",
      weatherIcon: "☀️",
      temperature: "32°C",
      activities: "Train: Paris → Valence TGV (11:56 – 14:05)\nCar Rental Pickup: 14:30\nWedding Ceremony: 15:00 at Chabeuil City Hall\nDinner & Party: 17:00 at Chanteperdrix Domain, Allex",
      accommodation: "Auberge La Plaine",
      emoji: "🚗",
      quickLinks: [
        {
          type: "train",
          text: "🚄 Paris → Valence Train",
          file: "July26_Train_Paris_Valence.pdf",
        },
        {
          type: "car",
          text: "🚗 Car Rental Pickup",
          file: "July26_Car_Rental_Valence.pdf",
        },
        {
          type: "hotel",
          text: "🏨 Auberge La Plaine",
          file: "July26_Hotel_Auberge_La_Plaine.pdf",
        },
      ],
    },
    {
      date: "Sun, July 27",
      location: "Chabeuil → Geneva",
      googleMapsQuery: "ibis budget Genève Aéroport, Geneva, Switzerland",
      type: "weekend",
      status: "Day Off",
      weather: "partly-cloudy",
      weatherIcon: "⛅",
      temperature: "24°C",
      activities: "Wedding Brunch at Chanteperdrix Domain\nCar Return: Valence TGV by 14:30\nTrain: Valence TGV → Geneva (15:14 – 15:50)",
      accommodation: "ibis budget Genève Aéroport",
      emoji: "🥐",
      quickLinks: [
        {
          type: "train",
          text: "🚄 Valence → Geneva Train",
          file: "July27_Train_Valence_Geneva.pdf",
        },
        {
          type: "hotel",
          text: "🏨 ibis budget Geneva",
          file: "July27-28_Hotel_ibis_Geneva.pdf",
        },
      ],
    },
    {
      date: "Mon, July 28",
      location: "Geneva",
      googleMapsQuery: "Geneva, Switzerland",
      type: "work-day",
      status: "Work Day",
      weather: "cloudy",
      weatherIcon: "☁️",
      temperature: "21°C",
      activities: "Remote work day",
      accommodation: "ibis budget Genève Aéroport",
      emoji: "🚄",
    },
    {
      date: "Tue, July 29",
      location: "Geneva → Heidelberg",
      googleMapsQuery: "NH Collection Heidelberg, Heidelberg, Germany",
      type: "work-day",
      status: "Work Day",
      weather: "rainy",
      weatherIcon: "🌧️",
      temperature: "18°C",
      activities: "Train: Geneva Station → Heidelberg Hbf (10:05 - 15:34)\nWork on train",
      accommodation: "NH Collection Heidelberg (2 nights)",
      emoji: "📍",
      quickLinks: [
        {
          type: "train",
          text: "🚄 Geneva → Heidelberg Train",
          file: "July29_Train_Geneva_Heidelberg.pdf",
        },
        {
          type: "hotel",
          text: "🏨 NH Collection Heidelberg",
          file: "July29-30_Hotel_NH_Heidelberg.pdf",
        },
      ],
    },
    {
      date: "Wed, July 30",
      location: "Heidelberg",
      googleMapsQuery: "Heidelberg, Germany",
      type: "work-day",
      status: "Work Day",
      weather: "partly-cloudy",
      weatherIcon: "⛅",
      temperature: "22°C",
      activities: "Erez's meeting in Heidelberg\nRemote work day",
      accommodation: "NH Collection Heidelberg",
      emoji: "👔",
    },
    {
      date: "Thu, July 31",
      location: "Heidelberg → Munich",
      googleMapsQuery: "NYX Hotel Munich, Munich, Germany",
      type: "work-day",
      status: "Work Day",
      weather: "sunny",
      weatherIcon: "☀️",
      temperature: "26°C",
      activities: "Train: Heidelberg → Munich (16:13 - 19:27)\nCar pickup: 20:00 Munich",
      accommodation: "NYX Hotel Munich (3 nights)",
      emoji: "🚉",
      quickLinks: [
        {
          type: "train",
          text: "🚄 Heidelberg → Munich Train",
          file: "July31_Train_Heidelberg_Munich.pdf",
        },
        {
          type: "car",
          text: "🚗 Car Pickup Munich",
          file: "July31_Car_Pickup_Munich.pdf",
        },
        {
          type: "hotel",
          text: "🏨 NYX Hotel Munich",
          file: "July31-Aug2_Hotel_NYX_Munich.pdf",
        },
      ],
    },
    {
      date: "Fri, Aug 1",
      location: "Munich",
      googleMapsQuery: "Munich, Germany",
      type: "weekend",
      status: "Day Off",
      weather: "sunny",
      weatherIcon: "☀️",
      temperature: "29°C",
      activities: "Explore Munich: Museums, parks, beer gardens\nCar return by 20:00",
      accommodation: "NYX Hotel Munich",
      emoji: "🏙️",
    },
    {
      date: "Sat, Aug 2",
      location: "Munich",
      googleMapsQuery: "Munich, Germany",
      type: "weekend",
      status: "Day Off",
      weather: "sunny",
      weatherIcon: "☀️",
      temperature: "31°C",
      activities: "Explore Munich: Museums, parks, beer gardens",
      accommodation: "NYX Hotel Munich",
      emoji: "🏙️",
    },
    {
      date: "Sun, Aug 3",
      location: "Munich → Israel",
      googleMapsQuery: "Munich Airport, Munich, Germany",
      type: "weekend",
      status: "Travel Day",
      weather: "partly-cloudy",
      weatherIcon: "⛅",
      temperature: "27°C",
      activities: "Flight: Munich → Tel Aviv at 10:20 AM\nArrive Tel Aviv at 15:00",
      accommodation: "Home",
      emoji: "✈️",
    },
  ];
  
  // Document URLs configuration
  const documentUrls = {
    // Hotel bookings
    "July17_Hotel_London_Victoria.pdf": "https://drive.google.com/file/d/1La618e68KwAWMHgnbDW1YWkg0RaBoOsx/view?usp=drive_link",
    "July20-22_Hotel_CitizenM_London.pdf": "https://drive.google.com/file/d/1px2vqsL0SPMNlaR-YNlIh5HBhixawBNR/view?usp=drive_link",
    "July23-25_Hotel_CitizenM_Paris.pdf": "https://drive.google.com/file/d/1dnjYdEO0td4BrKYkcxa0ZMmLvXnkVnr-/view?usp=drive_link",
    "July26_Hotel_Auberge_La_Plaine.pdf": "https://drive.google.com/file/d/1MoDAhSmHO1lF5Vj96PV25X4Qqg_KO-c7/view?usp=drive_link",
    "July27-28_Hotel_ibis_Geneva.pdf": "https://drive.google.com/file/d/1Z6mhgMrHtz5cSzIvFDytRus3OslwEC1n/view?usp=drive_link",
    "July29-30_Hotel_NH_Heidelberg.pdf": "https://drive.google.com/file/d/1ktrbl4Cw00iIsUZjgG8ymjairAbQbPxr/view?usp=drive_link",
    "July31-Aug2_Hotel_NYX_Munich.pdf": "https://drive.google.com/file/d/1ktrbl4Cw00iIsUZjgG8ymjairAbQbPxr/view?usp=drive_link",
    
    // Car rentals
    "July26_Car_Rental_Valence.pdf": "https://drive.google.com/file/d/1hdUrvE_vnPQi6ZatBsjwzQTn-wwobqXL/view?usp=drive_link",
    "July31_Car_Pickup_Munich.pdf": "https://drive.google.com/file/d/1QTu4NDrCJivKlbgpn2BZJ2LxKdsQ12OL/view?usp=drive_link",
  };
  
  // Train ticket URLs for each person
  const trainTicketUrls = {
    erez: {
      "July23_Train_London_Paris.pdf": "https://drive.google.com/file/d/1bSk5h8lhagnZDnC5eVYkLZiVutalFn0k/view?usp=drive_link",
      "July26_Train_Paris_Valence.pdf": "https://drive.google.com/file/d/1KIc4axr-8LSKX6mzzVcvqUiOnZM4vChc/view?usp=drive_link",
      "July27_Train_Valence_Geneva.pdf": "https://drive.google.com/file/d/1_2c2T4-X2m0Km3j21X01OlqBt5f5xmOR/view?usp=drive_link",
      "July29_Train_Geneva_Heidelberg.pdf": "https://drive.google.com/file/d/1E3RCnOU4IAF9Fjz5ajQlrscaR3ZAJVOP/view?usp=drive_link",
      "July31_Train_Heidelberg_Munich.pdf": "https://drive.google.com/file/d/1eiqyzyutAsaKQKG3u3eDvtW880EHtCHk/view?usp=drive_link",
    },
    shir: {
      "July23_Train_London_Paris.pdf": "https://drive.google.com/file/d/1xDSObpxz0TzrtOTRbTeuYha8lMOe_iyo/view?usp=drive_link",
      "July26_Train_Paris_Valence.pdf": "https://drive.google.com/file/d/1Jzn4agCYDYKQ1x1-A65X6HT2lwwM0XK6/view?usp=drive_link",
      "July27_Train_Valence_Geneva.pdf": "https://drive.google.com/file/d/1icVTPDZpyCgdxTGd70VeZd-IQ61LH699/view?usp=drive_link",
      "July29_Train_Geneva_Heidelberg.pdf": "https://drive.google.com/file/d/1I_V99CDWa0lQPsrO7Im5M4C1p3vPhEj_/view?usp=drive_link",
      "July31_Train_Heidelberg_Munich.pdf": "https://drive.google.com/file/d/1o2vST4XD2muU-HZKB_8G0i0q_uKtP0qd/view?usp=drive_link",
    },
  };
  
  // Drive folder URLs
  const folderUrls = {
    trains: "https://drive.google.com/drive/folders/1yRgqbTTE_N6MrdU3zXckWJV3vdEcqJhK?usp=drive_link",
    hotels: "https://drive.google.com/drive/folders/19gpOd77mMQeqZgfD9Xk1xdQfowbH3jV8?usp=drive_link",
    car: "https://drive.google.com/drive/folders/1cp6lxrTiQuxiZvAmpj0luaQSEMRnXCwM?usp=drive_link",
  };